version: '3.8'

services:
  frontend:
      build: 
        context: ./app
      container_name: airbnb_frontend
      volumes:
        - ./app/:/app/
      ports:
        - 5002:5002
      tty: true
      networks:
        - airbnb

  frontend_nginx:
      build:
        context: ./web
      container_name: airbnb_frontend_nginx
      ports:
        - "10052:10052"
      environment:
        TZ: 'Asia/Tokyo'
      volumes:
        - ./web/conf/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - airbnb
      depends_on:
        - frontend
  
      
networks:
  airbnb:
    name: airbnb
    driver: bridge